### PR TITLE
Add & Style Houzz Icon

### PR DESCRIPTION
**Pull request by codyalder**

### CODE REVIEW

**Comment by zimbatm** [comment]
Hi, what is houzz and is it notable enough to be added to the list ? We are trying to keep the set quite small to avoid too much load for the client.

**Comment by codyalder** [comment]
Hello!

Houzz is a web site and online community about architecture, interior
design and decorating, landscape design and home improvement, and they are
pretty large in that space.

Here is their site: http://www.houzz.com/

I work in a small web design shop/CMS builder, we have been getting a ton
of people asking for this particular icon so I figured why not go ahead and
show the initiative. Anyway let me know if you have any questions or if
something looks wonky.


On Thu, Mar 31, 2016 at 5:02 AM, zimbatm <notifications@github.com> wrote:

> Hi, what is houzz and is it notable enough to be added to the list ? We
> are trying to keep the set quite small to avoid too much load for the
> client.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/smcllns/css-social-buttons/pull/97#issuecomment-203860422>
>



-- 
*Cody Alder*
Designer

*SpaceCraft, Inc.*
701 Brazos Street, Suite 950
Austin, TX 78701

*W*  www.gospacecraft.com
*E * cody@gospacecraft.com

**Comment by zimbatm** [comment]
I've merged too soon, something seems to be broken: http://zocial.smcllns.com/sample.html#

**Comment by codyalder** [comment]
I'm not seeing a problem, what's the issue you're seeing? Let me know, and I'll get it fixed.

**Comment by zimbatm** [comment]
Looks fine now. Probably was just caching.

**Pull request merged**
