### PR TITLE
add wechat and alipay

### PR DESCRIPTION
**Pull request by Martindlut**
Could you please help review the change? Thanks!

### CODE REVIEW

**Comment by winniehell** [comment]
@Martindlut @zimbatm This is how the buttons look for me on current `master`. Do they look different on your systems?
buttons

**Comment by winniehell** [comment]
It seems like WeChat and AliPay are the only SVGs with colors. Also both consists only of an embedded PNG while the other icons seem to be vectors.

cc @smcllns

**Comment by zimbatm** [comment]
@Martindlut I'm sorry but I had to revert your contribution, the icons weren't displaying properly for me either

**Comment by zimbatm** [comment]
I don't have the time to fix the contribution so that's why I'm reverting. If you submit a fixed version I will happily have them merged again.

**Pull request merged**
